export const states = [
  {
    code: 'UP',
    name: 'Uttar Pradesh',
    type: 'State',
    districts: [
      { name: 'Agra' },
      { name: 'Aligarh' },
      { name: 'Allahabad' },
      { name: 'Ambedkar Nagar' },
      { name: 'Amethi' },
      { name: 'Amroha' },
      { name: 'Auraiya' },
      { name: 'Ayodhya' },
      { name: 'Azamgarh' },
      { name: 'Baghpat' },
      { name: 'Bahraich' },
      { name: 'Ballia' },
      { name: 'Balrampur' },
      { name: 'Banda' },
      { name: 'Barabanki' },
      { name: 'Bareilly' },
      { name: 'Basti' },
      { name: 'Bhadohi' },
      { name: 'Bijnor' },
      { name: 'Budaun' },
      { name: 'Bulandshahr' },
      { name: 'Chandauli' },
      { name: 'Chitrakoot' },
      { name: 'Deoria' },
      { name: 'Etah' },
      { name: 'Etawah' },
      { name: 'Farrukhabad' },
      { name: 'Fatehpur' },
      { name: 'Firozabad' },
      { name: 'Gautam Buddha Nagar' },
      { name: 'Ghaziabad' },
      { name: 'Ghazipur' },
      { name: 'Gonda' },
      { name: 'Gorakhpur' },
      { name: 'Hamirpur' },
      { name: 'Hapur' },
      { name: 'Hardoi' },
      { name: 'Hathras' },
      { name: 'Jalaun' },
      { name: 'Jaunpur' },
      { name: 'Jhansi' },
      { name: 'Kannauj' },
      { name: 'Kanpur Dehat' },
      { name: 'Kanpur Nagar' },
      { name: 'Kasganj' },
      { name: 'Kaushambi' },
      { name: 'Kheri' },
      { name: 'Kushinagar' },
      { name: 'Lalitpur' },
      { name: 'Lucknow' },
      { name: 'Maharajganj' },
      { name: 'Mahoba' },
      { name: 'Mainpuri' },
      { name: 'Mathura' },
      { name: 'Mau' },
      { name: 'Meerut' },
      { name: 'Mirzapur' },
      { name: 'Moradabad' },
      { name: 'Muzaffarnagar' },
      { name: 'Pilibhit' },
      { name: 'Pratapgarh' },
      { name: 'Prayagraj' },
      { name: 'Raebareli' },
      { name: 'Rampur' },
      { name: 'Saharanpur' },
      { name: 'Sambhal' },
      { name: 'Sant Kabir Nagar' },
      { name: 'Shahjahanpur' },
      { name: 'Shamli' },
      { name: 'Sharavasti' },
      { name: 'Siddharthnagar' },
      { name: 'Sitapur' },
      { name: 'Sonbhadra' },
      { name: 'Sultanpur' },
      { name: 'Unnao' },
      { name: 'Varanasi' },
    ]
  },
  {
    code: 'DL',
    name: 'Delhi',
    type: 'UT',
    districts: [
      { name: 'Central Delhi' },
      { name: 'East Delhi' },
      { name: 'New Delhi' },
      { name: 'North Delhi' },
      { name: 'North East Delhi' },
      { name: 'North West Delhi' },
      { name: 'Shahdara' },
      { name: 'South Delhi' },
      { name: 'South East Delhi' },
      { name: 'South West Delhi' },
      { name: 'West Delhi' },
    ]
  },
];
