-- AlterTable
ALTER TABLE "UserRoleMembership" ALTER COLUMN "validFrom" DROP NOT NULL,
ALTER COLUMN "validFrom" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "validTo" DROP NOT NULL,
ALTER COLUMN "validTo" SET DATA TYPE TIMESTAMPTZ(6);
